# -*- coding: utf-8 -*-
"""Thesis_preprocessing_csv_files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F9IoFfXQtsKkDuuBbsG1TQ9oXJQidVLS
"""

import pandas as pd

df1 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data",
                 names = ["ID number", "Diagnosis", "Radius", "Texture", "Perimetert", "Area", "Smoothness", "Compactness", "Concavity","Concave point", "Symmetry", "Fractal dimension", "unknown1", "unknown2", "unknown3", "unknown4", "unknown5", "unknown6", "unknown7", "unknown8", "unknown9", "unknown10", "unknown11", "unknown12", "unknown13", "unknown14", "unknown15", "unknown16", "unknown17", "unknown18", "unknown19", "unknown20"], decimal=",")

df1.head()

df1.to_csv("wdbc", index=False)

df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data",
                 names = ["Class name", "Handicapped infants", "Water project cost sharing", "Adoption of budget resolution", "Physician-free-freeze ", "El-salvador-aid", "religious-groups-in-schools", "anti-satellite-test-ban", "aid-to-nicaraguan-contras","mx-missile", "immigration", "synfuels-corporation-cutback", "education-spending", "superfund-right-to-sue", "crime", "duty-free-exports", "export-administration-act-south-africa"])
df2.head()

df2.to_csv("Congressional-voting-records", index=False)

df3 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data-original",
                 names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "car name"])
df3.head()